# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- staging
- trying

strategy:
  matrix:
    windows-stable:
      imageName: 'vs2017-win2016'
      rustup_toolchain: stable
      target: 'Windows'
    mac-stable:
      imageName: 'macos-10.14'
      rustup_toolchain: stable
      target: 'Darwin'
    linux-stable:
      imageName: 'ubuntu-16.04'
      rustup_toolchain: stable
      target: 'Linux'

pool:
  vmImage: $(imageName)

steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
    condition: ne( variables['Agent.OS'], 'Windows_NT' )
  - script: |
      curl -sSf -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
      echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
    displayName: Windows install rust
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
  - script: cargo build --all
    displayName: Build debug binary
  - script: cargo test --all
    displayName: Run tests
  - script: cargo build --all --release
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    displayName: Build optimized binary for release
  - task: CopyFiles@2
    displayName: Copy assets
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/target/release'
      contents: |
        mdformat
      targetFolder: '$(Build.BinariesDirectory)'
  - task: ArchiveFiles@2
    displayName: Compress binary
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)/mdformat'
      archiveType: 'tar'
      tarCompression: 'gz'
      archiveFile: '$(Build.ArtifactStagingDirectory)/mdformat-$(target).tar.gz'
  - bash: |
      MY_TAG="$(Build.SourceBranch)"
      MY_TAG=${MY_TAG#refs/tags/}
      echo $MY_TAG
      echo "##vso[task.setvariable variable=build.my_tag]$MY_TAG"
    displayName: "Create tag variable"
  - task: GithubRelease@0
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    displayName: 'Create Github release'
    inputs:
      githubConnection: afnanenayetgh
      repositoryName: afnanenayet/mdformat
      action: 'edit'
      tag: '$(build.my_tag)'
      tagSource: 'manual'
      title: '$(build.my_tag)'
      compareWith: 'lastFullRelease'
      addChangeLog: true
      assets: '$(Build.ArtifactStagingDirectory)/mdformat-$(target).tar.gz'
      assetUploadMode: 'replace'
